# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false
right_format = "$nodejs $time"

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
disabled = false
error_symbol = "[❫](bold red)"
format = "$symbol "
success_symbol = "[❫](bold green)"
vimcmd_replace_one_symbol = "[❪](bold purple)"
vimcmd_replace_symbol = "[❪](bold purple)"
vimcmd_symbol = "[❪](bold green)"
vimcmd_visual_symbol = "[❪](bold yellow)"

[line_break]
disabled = true

[time]
disabled = false
format = "[$time]($style) "

[nodejs]
format = "[$symbol($version )]($style)"

[git_status]
disabled = false
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
conflicted = "=${count}"
deleted = "✘${count}"
modified = "!${count}"
renamed = "»${count}"
staged = "+${count}"
stashed = "*${count}"
untracked = "?${count}"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
