#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output DP-2 --primary --mode 2560x1440 --rotate normal --output DP-0 --mode 1920x1080 --rotate normal --right-of DP-2
xsetroot -cursor_name left_ptr

bspc monitor DP-2 -d 1 2 3 4 5
bspc monitor DP-0 -d 6 7 8 9 0

bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 				 0
bspc config focused_border_color \#1AAC60

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Gpick state=floating follow=on center=on rectangle=800x600+0+0
bspc rule -a Pavucontrol state=floating follow=on center=on rectangle=800x600+0+0
bspc rule -a Google-chrome desktop='^2'
bspc rule -a Spotify desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

picom &
dunst &
nm-applet &
pa-applet &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
$HOME/.config/polybar/launch.sh
# feh --bg-fill /run/media/Disco-1/Imágenes/Wallpapers/24577-4k-minimalist-wallpaper-3840x2160-158074280832820.jpg
feh --bg-fill /run/media/Disco-1/Imágenes/Wallpapers/mikael_4.jpg
